// ============================================================
// Seed Products — 8 sản phẩm demo
// ============================================================
const { getDB, initDB, transaction } = require("../config/database");

const products = [
  {
    name: "Château Lafite Rothschild",
    region: "Pháp",
    subregion: "Bordeaux",
    type: "red",
    grape: "Cabernet Sauvignon",
    abv: 13.5,
    volume: "750ml",
    price: 18500000,
    old_price: 21000000,
    stock: 12,
    score: 98,
    rating: 4.9,
    reviews_count: 234,
    vintage: 2018,
    badge: "Best Seller",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ rubis sâu",
      nose: "Cassis, hương gỗ sồi, hoa violets",
      palate: "Tannic mịn, thanh lịch, phức hợp",
      finish: "Dài >90 giây",
    }),
    food_pairing: JSON.stringify([
      "Bò bít tết",
      "Thịt cừu nướng",
      "Pho mát cứng",
    ]),
    tags: JSON.stringify(["premium", "collection", "gift"]),
  },
  {
    name: "Domaine de la Romanée-Conti",
    region: "Pháp",
    subregion: "Burgundy",
    type: "red",
    grape: "Pinot Noir",
    abv: 13,
    volume: "750ml",
    price: 95000000,
    old_price: null,
    stock: 3,
    score: 100,
    rating: 5,
    reviews_count: 48,
    vintage: 2017,
    badge: "Hiếm",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ garnet trong suốt",
      nose: "Cherry đỏ, hoa hồng, đất quý",
      palate: "Tinh tế, phức hợp phi thường",
      finish: ">2 phút",
    }),
    food_pairing: JSON.stringify([
      "Phô mai Comté",
      "Nấm truffle",
      "Cá hồi hun khói",
    ]),
    tags: JSON.stringify(["luxury", "rare", "collection"]),
  },
  {
    name: "Opus One Reserve",
    region: "Mỹ",
    subregion: "Napa Valley",
    type: "red",
    grape: "Cabernet Sauvignon blend",
    abv: 14.5,
    volume: "750ml",
    price: 12800000,
    old_price: 14500000,
    stock: 24,
    score: 96,
    rating: 4.8,
    reviews_count: 187,
    vintage: 2019,
    badge: "Mới về",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ tím đậm",
      nose: "Mứt mận, chocolate đen, vanilla",
      palate: "Dày dặn, mượt mà",
      finish: "Dài ấm áp",
    }),
    food_pairing: JSON.stringify([
      "Sườn bò nướng BBQ",
      "Xốt nấm rừng",
      "Phô mai cheddar",
    ]),
    tags: JSON.stringify(["premium", "new"]),
  },
  {
    name: "Dom Pérignon Vintage",
    region: "Pháp",
    subregion: "Champagne",
    type: "sparkling",
    grape: "Chardonnay / Pinot Noir",
    abv: 12.5,
    volume: "750ml",
    price: 7200000,
    old_price: 8500000,
    stock: 36,
    score: 97,
    rating: 4.9,
    reviews_count: 312,
    vintage: 2013,
    badge: "Sale 15%",
    img: "images/champagne_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Vàng rơm óng ánh",
      nose: "Bánh mì nướng, chanh vàng, acacia",
      palate: "Sủi bọt mịn, tinh tế",
      finish: "Tươi mát dài",
    }),
    food_pairing: JSON.stringify([
      "Hải sản tươi",
      "Oyster",
      "Caviar",
      "Sashimi",
    ]),
    tags: JSON.stringify(["champagne", "gift", "celebration"]),
  },
  {
    name: "Macallan 25 Year Sherry Oak",
    region: "Scotland",
    subregion: "Speyside",
    type: "whisky",
    grape: null,
    abv: 43,
    volume: "700ml",
    price: 52000000,
    old_price: null,
    stock: 5,
    score: 95,
    rating: 4.9,
    reviews_count: 89,
    vintage: null,
    badge: "Siêu hiếm",
    img: "images/whisky_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Amber vàng tươi",
      nose: "Sherry ngọt, vanilla, gừng",
      palate: "Mịn như nhung, phong phú",
      finish: "Rất dài ấm áp",
    }),
    food_pairing: JSON.stringify([
      "Chocolate đen",
      "Cigar Cuba",
      "Phô mai cứng",
    ]),
    tags: JSON.stringify(["whisky", "luxury", "rare"]),
  },
  {
    name: "Sassicaia 2020",
    region: "Ý",
    subregion: "Bolgheri",
    type: "red",
    grape: "Cabernet Sauvignon",
    abv: 13.5,
    volume: "750ml",
    price: 6800000,
    old_price: 7500000,
    stock: 30,
    score: 94,
    rating: 4.7,
    reviews_count: 156,
    vintage: 2020,
    badge: null,
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ rubis đậm",
      nose: "Blackberry, ceder, herbs Địa Trung Hải",
      palate: "Đậm đà, cấu trúc tốt",
      finish: "Dài và nhất quán",
    }),
    food_pairing: JSON.stringify([
      "Pasta thịt bò",
      "Pizza thịt nguội",
      "Cá ngừ tươi",
    ]),
    tags: JSON.stringify(["italian", "premium"]),
  },
  {
    name: "Cloudy Bay Sauvignon Blanc",
    region: "New Zealand",
    subregion: "Marlborough",
    type: "white",
    grape: "Sauvignon Blanc",
    abv: 13,
    volume: "750ml",
    price: 850000,
    old_price: 1000000,
    stock: 120,
    score: 91,
    rating: 4.5,
    reviews_count: 428,
    vintage: 2022,
    badge: "Bán chạy",
    img: "images/white_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Vàng nhạt trong suốt",
      nose: "Chanh dây, lý chua, cỏ mới cắt",
      palate: "Sắc sảo, tươi mát",
      finish: "Thanh và sạch",
    }),
    food_pairing: JSON.stringify(["Gỏi hải sản", "Sushi", "Salad rau thơm"]),
    tags: JSON.stringify(["white", "everyday"]),
  },
  {
    name: "Concha y Toro Don Melchor",
    region: "Chile",
    subregion: "Puente Alto",
    type: "red",
    grape: "Cabernet Sauvignon",
    abv: 14.5,
    volume: "750ml",
    price: 2200000,
    old_price: 2800000,
    stock: 58,
    score: 93,
    rating: 4.6,
    reviews_count: 203,
    vintage: 2020,
    badge: "Combo tiết kiệm",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ tím thẫm",
      nose: "Cassis chín, café espresso, hương gỗ",
      palate: "Đầy đặn, cân bằng xuất sắc",
      finish: "Dài và tinh tế",
    }),
    food_pairing: JSON.stringify(["Bò wagyu", "Lamb chop", "Dark chocolate"]),
    tags: JSON.stringify(["value", "south-america"]),
  },
  {
    name: "Penfolds Grange",
    region: "Úc",
    subregion: "South Australia",
    type: "red",
    grape: "Shiraz",
    abv: 14.5,
    volume: "750ml",
    price: 9500000,
    old_price: 11000000,
    stock: 18,
    score: 97,
    rating: 4.8,
    reviews_count: 143,
    vintage: 2018,
    badge: "Iconic",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ tím sậm",
      nose: "Mận chín, chocolate, hương hồi và gỗ sồi",
      palate: "Đậm đà, hùng hậu, tanin rất mịn",
      finish: "Cực dài, ấm áp",
    }),
    food_pairing: JSON.stringify([
      "Kangaroo steak",
      "Bò nướng BBQ",
      "Phô mai xanh",
    ]),
    tags: JSON.stringify(["australian", "premium", "iconic"]),
  },
  {
    name: "Vega Sicilia Único",
    region: "Tây Ban Nha",
    subregion: "Ribera del Duero",
    type: "red",
    grape: "Tempranillo / Cabernet",
    abv: 14,
    volume: "750ml",
    price: 14500000,
    old_price: null,
    stock: 6,
    score: 98,
    rating: 4.9,
    reviews_count: 67,
    vintage: 2012,
    badge: "Hiếm có",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ garnet già",
      nose: "Cherry đen, da thuộc, hương thảo mộc Tây Ban Nha",
      palate: "Tinh tế, cân bằng hoàn hảo, đa tầng",
      finish: "Kéo dài vô tận",
    }),
    food_pairing: JSON.stringify(["Jamón ibérico", "Chorizo", "Thịt cừu quay"]),
    tags: JSON.stringify(["spanish", "luxury", "rare"]),
  },
  {
    name: "Moët & Chandon Ice Impérial",
    region: "Pháp",
    subregion: "Champagne",
    type: "sparkling",
    grape: "Pinot Noir / Chardonnay / Meunier",
    abv: 12,
    volume: "750ml",
    price: 2200000,
    old_price: 2600000,
    stock: 80,
    score: 90,
    rating: 4.5,
    reviews_count: 521,
    vintage: null,
    badge: "Sale 15%",
    img: "images/champagne_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Vàng nhạt với bọt nhỏ li ti",
      nose: "Đào, lê, hoa nhài",
      palate: "Ngọt mát, sủi bọt dịu, tươi trẻ",
      finish: "Thanh mát, dứt khoát",
    }),
    food_pairing: JSON.stringify([
      "Đá bào trái cây",
      "Mousse chanh",
      "Cocktail party",
    ]),
    tags: JSON.stringify(["champagne", "party", "gift"]),
  },
  {
    name: "Johnnie Walker Blue Label",
    region: "Scotland",
    subregion: "Blended",
    type: "whisky",
    grape: null,
    abv: 40,
    volume: "750ml",
    price: 5200000,
    old_price: 5800000,
    stock: 45,
    score: 92,
    rating: 4.7,
    reviews_count: 388,
    vintage: null,
    badge: "Quà tặng",
    img: "images/whisky_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "琥珀 vàng sâu",
      nose: "Honey, vanilla, trái cây sấy khô",
      palate: "Mượt mà, phong phú, vị khói nhẹ",
      finish: "Ấm áp, dài",
    }),
    food_pairing: JSON.stringify([
      "Cigar",
      "Chocolate trắng",
      "Cá hồi xông khói",
    ]),
    tags: JSON.stringify(["whisky", "gift", "blended"]),
  },
  {
    name: "Whispering Angel Rosé",
    region: "Pháp",
    subregion: "Provence",
    type: "rosé",
    grape: "Grenache / Cinsault / Rolle",
    abv: 13,
    volume: "750ml",
    price: 1450000,
    old_price: 1700000,
    stock: 65,
    score: 91,
    rating: 4.6,
    reviews_count: 276,
    vintage: 2022,
    badge: "Mùa hè",
    img: "images/rose_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Hồng phấn nhạt, trong suốt",
      nose: "Dâu tây, đào trắng, hoa hồng",
      palate: "Tươi, nhẹ nhàng, cân bằng tuyệt vời",
      finish: "Sạch, dứt khoát",
    }),
    food_pairing: JSON.stringify(["Salad Niçoise", "Tôm nướng", "Phô mai dê"]),
    tags: JSON.stringify(["rosé", "summer", "provence"]),
  },
  {
    name: "Remy Martin XO",
    region: "Pháp",
    subregion: "Cognac",
    type: "brandy",
    grape: null,
    abv: 40,
    volume: "700ml",
    price: 4800000,
    old_price: 5500000,
    stock: 22,
    score: 94,
    rating: 4.8,
    reviews_count: 192,
    vintage: null,
    badge: "Sang trọng",
    img: "images/cognac_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Amber đỏ sâu",
      nose: "Mận khô, cam quýt, hoa jasmine, hương gỗ",
      palate: "Mượt, ấm, vị trái cây chín và gia vị",
      finish: "Rất dài, hoa quả và gỗ",
    }),
    food_pairing: JSON.stringify([
      "Foie gras",
      "Phô mai brie",
      "Socola truffle",
    ]),
    tags: JSON.stringify(["cognac", "brandy", "luxury", "gift"]),
  },
  {
    name: "Gaja Barbaresco",
    region: "Ý",
    subregion: "Piedmont",
    type: "red",
    grape: "Nebbiolo",
    abv: 14,
    volume: "750ml",
    price: 7800000,
    old_price: null,
    stock: 14,
    score: 96,
    rating: 4.8,
    reviews_count: 109,
    vintage: 2019,
    badge: "Cổ điển",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ garnet với viền cam",
      nose: "Hoa hồng khô, cherry dại, nhựa trắng",
      palate: "Đậm đà nhưng tinh tế, tanin mạnh mẽ",
      finish: "Dài với hương hoa và đất",
    }),
    food_pairing: JSON.stringify([
      "Risotto nấm truffle",
      "Thịt bò hầm Barolo",
      "Phô mai Parmesan",
    ]),
    tags: JSON.stringify(["italian", "premium", "nebbiolo"]),
  },
  {
    name: "Egon Müller Scharzhofberger Riesling TBA",
    region: "Đức",
    subregion: "Mosel",
    type: "white",
    grape: "Riesling",
    abv: 7,
    volume: "375ml",
    price: 22000000,
    old_price: null,
    stock: 4,
    score: 100,
    rating: 5,
    reviews_count: 23,
    vintage: 2020,
    badge: "Quý hiếm",
    img: "images/white_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Vàng mật ong óng ánh",
      nose: "Mật ong, mơ sấy, cam quýt, khoáng chất",
      palate: "Cực ngọt nhưng tươi, cân bằng siêu việt",
      finish: "Vĩnh cửu, hơn 3 phút",
    }),
    food_pairing: JSON.stringify([
      "Foie gras",
      "Roquefort",
      "Bánh flan caramel",
    ]),
    tags: JSON.stringify(["germany", "dessert", "luxury", "rare"]),
  },
  {
    name: "Screaming Eagle Cabernet",
    region: "Mỹ",
    subregion: "Napa Valley",
    type: "red",
    grape: "Cabernet Sauvignon",
    abv: 14.5,
    volume: "750ml",
    price: 75000000,
    old_price: null,
    stock: 2,
    score: 99,
    rating: 5,
    reviews_count: 31,
    vintage: 2016,
    badge: "Huyền thoại",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ tím sậm huyền bí",
      nose: "Cassis, mận đen, graphite, hương hoa violet",
      palate: "Hoàn hảo, phức hợp vô song, tanin như nhung",
      finish: "Bất tận, tinh khiết",
    }),
    food_pairing: JSON.stringify([
      "A5 Wagyu",
      "Lobster bisque",
      "Phô mai Époisses",
    ]),
    tags: JSON.stringify(["usa", "luxury", "cult", "rare"]),
  },
  {
    name: "Torres Gran Coronas",
    region: "Tây Ban Nha",
    subregion: "Penedès",
    type: "red",
    grape: "Cabernet Sauvignon / Tempranillo",
    abv: 13.5,
    volume: "750ml",
    price: 650000,
    old_price: 800000,
    stock: 200,
    score: 89,
    rating: 4.4,
    reviews_count: 364,
    vintage: 2020,
    badge: "Tiết kiệm",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ cherry tươi sáng",
      nose: "Cherry, plum, hương thảo mộc",
      palate: "Trung bình, tươi, dễ uống",
      finish: "Vừa phải, trái cây",
    }),
    food_pairing: JSON.stringify(["Tapas", "Pizza", "Thịt nướng thông thường"]),
    tags: JSON.stringify(["spanish", "everyday", "value"]),
  },
  {
    name: "Cloudy Bay Te Koko",
    region: "New Zealand",
    subregion: "Marlborough",
    type: "white",
    grape: "Sauvignon Blanc",
    abv: 14,
    volume: "750ml",
    price: 1850000,
    old_price: 2200000,
    stock: 38,
    score: 93,
    rating: 4.7,
    reviews_count: 148,
    vintage: 2020,
    badge: "Đặc biệt",
    img: "images/white_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Vàng rơm đậm",
      nose: "Bơ, đào vàng, vanilla, hương sồi tinh tế",
      palate: "Phong phú, béo ngậy, phức hợp",
      finish: "Dài và mượt mà",
    }),
    food_pairing: JSON.stringify([
      "Bơ tôm hùm",
      "Gà quay kem nấm",
      "Pasta carbonara",
    ]),
    tags: JSON.stringify(["white", "oaked", "premium"]),
  },
  {
    name: "Château d'Yquem",
    region: "Pháp",
    subregion: "Sauternes",
    type: "dessert",
    grape: "Sémillon / Sauvignon Blanc",
    abv: 14,
    volume: "375ml",
    price: 8500000,
    old_price: null,
    stock: 9,
    score: 98,
    rating: 4.9,
    reviews_count: 76,
    vintage: 2015,
    badge: "Vang ngọt đỉnh cao",
    img: "images/dessert_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Vàng mật ong óng ánh",
      nose: "Mơ sấy, mật ong, hoa acacia, gừng",
      palate: "Ngọt ngào uy nghi, cân bằng hoàn hảo bởi độ acid",
      finish: "Vô tận, mật hoa",
    }),
    food_pairing: JSON.stringify([
      "Foie gras",
      "Tôm hùm sốt bơ",
      "Phô mai Roquefort",
    ]),
    tags: JSON.stringify(["dessert", "luxury", "sauternes"]),
  },
  {
    name: "Glenfiddich 18 Year",
    region: "Scotland",
    subregion: "Speyside",
    type: "whisky",
    grape: null,
    abv: 40,
    volume: "700ml",
    price: 2100000,
    old_price: 2500000,
    stock: 55,
    score: 91,
    rating: 4.6,
    reviews_count: 418,
    vintage: null,
    badge: "Bán chạy",
    img: "images/whisky_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Vàng amber ấm",
      nose: "Đào, lê, oak, mật ong nhẹ",
      palate: "Mượt mà, trái cây ngọt, vanilla",
      finish: "Ấm áp, vừa phải",
    }),
    food_pairing: JSON.stringify([
      "Chocolate sữa",
      "Hạt điều rang",
      "Phô mai cheddar",
    ]),
    tags: JSON.stringify(["whisky", "single-malt", "everyday"]),
  },
  {
    name: "Clos du Val Estate Chardonnay",
    region: "Mỹ",
    subregion: "Napa Valley",
    type: "white",
    grape: "Chardonnay",
    abv: 14.2,
    volume: "750ml",
    price: 1200000,
    old_price: 1450000,
    stock: 42,
    score: 90,
    rating: 4.5,
    reviews_count: 187,
    vintage: 2021,
    badge: null,
    img: "images/white_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Vàng rơm sáng",
      nose: "Táo vàng, bơ, vanilla, sồi nhẹ",
      palate: "Béo ngậy vừa phải, cân bằng tốt, tươi mát",
      finish: "Trung bình dài, trái cây",
    }),
    food_pairing: JSON.stringify([
      "Gà áp chảo bơ chanh",
      "Cá trắng nướng",
      "Risotto hải sản",
    ]),
    tags: JSON.stringify(["white", "usa", "chardonnay"]),
  },
  {
    name: "Pio Cesare Barolo DOCG",
    region: "Ý",
    subregion: "Barolo",
    type: "red",
    grape: "Nebbiolo",
    abv: 14.5,
    volume: "750ml",
    price: 3200000,
    old_price: 3800000,
    stock: 27,
    score: 93,
    rating: 4.7,
    reviews_count: 134,
    vintage: 2018,
    badge: "Giảm 15%",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ garnet viền cam nhạt",
      nose: "Hoa hồng khô, cherry đen, nhựa thơm, đất",
      palate: "Tanin mạnh nhưng thanh lịch, phức hợp",
      finish: "Dài, khô và khoáng",
    }),
    food_pairing: JSON.stringify([
      "Braised beef",
      "Truffle pasta",
      "Phô mai Parmigiano",
    ]),
    tags: JSON.stringify(["italian", "barolo", "premium"]),
  },
  {
    name: "Baileys Original Irish Cream",
    region: "Ireland",
    subregion: null,
    type: "liqueur",
    grape: null,
    abv: 17,
    volume: "700ml",
    price: 650000,
    old_price: 750000,
    stock: 150,
    score: 88,
    rating: 4.5,
    reviews_count: 862,
    vintage: null,
    badge: "Yêu thích",
    img: "images/cognac_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Nâu kem mịn màng",
      nose: "Kem tươi, chocolate sữa, whisky nhẹ",
      palate: "Ngọt ngào, béo, êm dịu",
      finish: "Ngắn, ngọt và kem",
    }),
    food_pairing: JSON.stringify([
      "Bánh tiramisu",
      "Ice cream",
      "Cà phê Irish",
    ]),
    tags: JSON.stringify(["liqueur", "everyday", "gift", "dessert"]),
  },
  {
    name: "Hennessy VSOP Privilege",
    region: "Pháp",
    subregion: "Cognac",
    type: "brandy",
    grape: null,
    abv: 40,
    volume: "700ml",
    price: 1900000,
    old_price: 2200000,
    stock: 90,
    score: 90,
    rating: 4.6,
    reviews_count: 534,
    vintage: null,
    badge: "Phổ biến",
    img: "images/cognac_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Amber vàng ấm áp",
      nose: "Hoa quả nướng, hương gỗ, vanilla",
      palate: "Mượt mà, cân bằng, ấm và tinh tế",
      finish: "Dài vừa, dứt khoát",
    }),
    food_pairing: JSON.stringify([
      "Sô cô la đen",
      "Trái cây sấy",
      "Phô mai gruyère",
    ]),
    tags: JSON.stringify(["cognac", "brandy", "everyday", "gift"]),
  },
  {
    name: "Masi Amarone della Valpolicella",
    region: "Ý",
    subregion: "Veneto",
    type: "red",
    grape: "Corvina / Molinara / Rondinella",
    abv: 15.5,
    volume: "750ml",
    price: 2800000,
    old_price: 3200000,
    stock: 32,
    score: 94,
    rating: 4.7,
    reviews_count: 178,
    vintage: 2017,
    badge: "Đậm đà",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ ruby đậm sẫm gần như tím",
      nose: "Anh đào đen, mận khô, socola đen, thuốc lá",
      palate: "Đậm đà, đầy đặn, phức hợp, tanin mềm",
      finish: "Rất dài, ấm",
    }),
    food_pairing: JSON.stringify([
      "Thịt bò hầm",
      "Phô mai Pecorino",
      "Risotto thịt",
    ]),
    tags: JSON.stringify(["italian", "amarone", "bold"]),
  },
  {
    name: "Kumeu River Chardonnay",
    region: "New Zealand",
    subregion: "Auckland",
    type: "white",
    grape: "Chardonnay",
    abv: 13.5,
    volume: "750ml",
    price: 1100000,
    old_price: 1300000,
    stock: 44,
    score: 93,
    rating: 4.6,
    reviews_count: 99,
    vintage: 2021,
    badge: null,
    img: "images/white_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Vàng xanh nhạt trong suốt",
      nose: "Táo xanh, nho, hoa trắng, sồi nhẹ",
      palate: "Tươi sáng, khoáng, ít gỗ, thanh lịch",
      finish: "Dài và sạch",
    }),
    food_pairing: JSON.stringify([
      "Cá sole áp chảo",
      "Tôm hùm không sốt",
      "Salad rau xanh",
    ]),
    tags: JSON.stringify(["white", "newzealand", "chardonnay"]),
  },
  {
    name: "Caymus Cabernet Sauvignon",
    region: "Mỹ",
    subregion: "Napa Valley",
    type: "red",
    grape: "Cabernet Sauvignon",
    abv: 14.8,
    volume: "750ml",
    price: 3600000,
    old_price: 4200000,
    stock: 35,
    score: 93,
    rating: 4.7,
    reviews_count: 289,
    vintage: 2021,
    badge: "Napa Favorite",
    img: "images/red_wine_bottle.jpg",
    description: "",
    tasting_notes: JSON.stringify({
      color: "Đỏ ruby đậm",
      nose: "Mứt mâm xôi, anh đào đen, vanilla, sồi ngọt",
      palate: "Đầy đặn, mềm mại, dễ tiếp cận, trái cây chín",
      finish: "Dài ấm, trái cây và gỗ",
    }),
    food_pairing: JSON.stringify([
      "Ribeye steak",
      "Bò bít tết",
      "BBQ sườn non",
    ]),
    tags: JSON.stringify(["usa", "napa", "premium"]),
  },
];

function seed() {
  initDB();
  const db = getDB();

  const insert = db.prepare(`
    INSERT OR IGNORE INTO products
      (name,region,subregion,type,grape,abv,volume,price,old_price,stock,score,rating,reviews_count,vintage,badge,img,description,tasting_notes,food_pairing,tags)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
  `);

  const insertAll = transaction(db, (rows) => {
    rows.forEach((r) => {
      insert.run(
        r.name,
        r.region,
        r.subregion,
        r.type,
        r.grape,
        r.abv,
        r.volume,
        r.price,
        r.old_price,
        r.stock,
        r.score,
        r.rating,
        r.reviews_count,
        r.vintage,
        r.badge,
        r.img,
        r.description,
        r.tasting_notes,
        r.food_pairing,
        r.tags,
      );
    });
  });
  insertAll(products);

  // Seed admin user
  const bcrypt = require("bcryptjs");
  const adminPwd = bcrypt.hashSync("Admin@123", 10);
  db.prepare(
    `
    INSERT OR IGNORE INTO users (email, password, full_name, role, tier)
    VALUES (?, ?, 'VINOVA Admin', 'admin', 'platinum')
  `,
  ).run("admin@vinova.vn", adminPwd);

  console.log(`✅ Seeded ${products.length} products + admin user`);
  console.log("   Email: admin@vinova.vn | Password: Admin@123");
}

seed();
