// ============================================================
// Seed Products — 8 sản phẩm demo
// ============================================================
const { getDB, initDB, transaction } = require("../config/database");

const products = [
    {
        name: "Château Lafite Rothschild", region: "Pháp", subregion: "Bordeaux", type: "red",
        grape: "Cabernet Sauvignon", abv: 13.5, volume: "750ml",
        price: 18500000, old_price: 21000000, stock: null, score: 98, rating: 4.9,
        reviews_count: 234, vintage: 2018, badge: "Best Seller",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Domaine de la Romanée-Conti", region: "Pháp", subregion: "Burgundy", type: "red",
        grape: "Pinot Noir", abv: 13.0, volume: "750ml",
        price: 95000000, old_price: null, stock: null, score: 100, rating: 5.0,
        reviews_count: 48, vintage: 2017, badge: "Hiếm",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Opus One Reserve", region: "Mỹ", subregion: "Napa Valley", type: "red",
        grape: "Cabernet Sauvignon blend", abv: 14.5, volume: "750ml",
        price: 12800000, old_price: 14500000, stock: null, score: 96, rating: 4.8,
        reviews_count: 187, vintage: 2019, badge: "Mới về",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Dom Pérignon Vintage", region: "Pháp", subregion: "Champagne", type: "sparkling",
        grape: "Chardonnay / Pinot Noir", abv: 12.5, volume: "750ml",
        price: 7200000, old_price: 8500000, stock: null, score: 97, rating: 4.9,
        reviews_count: 312, vintage: 2013, badge: "Sale 15%",
        img: "images/champagne_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Macallan 25 Year Sherry Oak", region: "Scotland", subregion: "Speyside", type: "whisky",
        grape: null, abv: 43.0, volume: "700ml",
        price: 52000000, old_price: null, stock: null, score: 95, rating: 4.9,
        reviews_count: 89, vintage: null, badge: "Siêu hiếm",
        img: "images/whisky_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Sassicaia 2020", region: "Ý", subregion: "Bolgheri", type: "red",
        grape: "Cabernet Sauvignon", abv: 13.5, volume: "750ml",
        price: 6800000, old_price: 7500000, stock: null, score: 94, rating: 4.7,
        reviews_count: 156, vintage: 2020, badge: null,
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Cloudy Bay Sauvignon Blanc", region: "New Zealand", subregion: "Marlborough", type: "white",
        grape: "Sauvignon Blanc", abv: 13.0, volume: "750ml",
        price: 850000, old_price: 1000000, stock: null, score: 91, rating: 4.5,
        reviews_count: 428, vintage: 2022, badge: "Bán chạy",
        img: "images/white_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Concha y Toro Don Melchor", region: "Chile", subregion: "Puente Alto", type: "red",
        grape: "Cabernet Sauvignon", abv: 14.5, volume: "750ml",
        price: 2200000, old_price: 2800000, stock: null, score: 93, rating: 4.6,
        reviews_count: 203, vintage: 2020, badge: "Combo tiết kiệm",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Penfolds Grange", region: "Úc", subregion: "South Australia", type: "red",
        grape: "Shiraz", abv: 14.5, volume: "750ml",
        price: 9500000, old_price: 11000000, stock: null, score: 97, rating: 4.8,
        reviews_count: 143, vintage: 2018, badge: "Iconic",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Vega Sicilia Único", region: "Tây Ban Nha", subregion: "Ribera del Duero", type: "red",
        grape: "Tempranillo / Cabernet", abv: 14.0, volume: "750ml",
        price: 14500000, old_price: null, stock: null, score: 98, rating: 4.9,
        reviews_count: 67, vintage: 2012, badge: "Hiếm có",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Moët & Chandon Ice Impérial", region: "Pháp", subregion: "Champagne", type: "sparkling",
        grape: "Pinot Noir / Chardonnay / Meunier", abv: 12.0, volume: "750ml",
        price: 2200000, old_price: 2600000, stock: null, score: 90, rating: 4.5,
        reviews_count: 521, vintage: null, badge: "Sale 15%",
        img: "images/champagne_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Johnnie Walker Blue Label", region: "Scotland", subregion: "Blended", type: "whisky",
        grape: null, abv: 40.0, volume: "750ml",
        price: 5200000, old_price: 5800000, stock: null, score: 92, rating: 4.7,
        reviews_count: 388, vintage: null, badge: "Quà tặng",
        img: "images/whisky_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Whispering Angel Rosé", region: "Pháp", subregion: "Provence", type: "rosé",
        grape: "Grenache / Cinsault / Rolle", abv: 13.0, volume: "750ml",
        price: 1450000, old_price: 1700000, stock: null, score: 91, rating: 4.6,
        reviews_count: 276, vintage: 2022, badge: "Mùa hè",
        img: "images/rose_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Remy Martin XO", region: "Pháp", subregion: "Cognac", type: "brandy",
        grape: null, abv: 40.0, volume: "700ml",
        price: 4800000, old_price: 5500000, stock: null, score: 94, rating: 4.8,
        reviews_count: 192, vintage: null, badge: "Sang trọng",
        img: "images/cognac_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Gaja Barbaresco", region: "Ý", subregion: "Piedmont", type: "red",
        grape: "Nebbiolo", abv: 14.0, volume: "750ml",
        price: 7800000, old_price: null, stock: null, score: 96, rating: 4.8,
        reviews_count: 109, vintage: 2019, badge: "Cổ điển",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Egon Müller Scharzhofberger Riesling TBA", region: "Đức", subregion: "Mosel", type: "white",
        grape: "Riesling", abv: 7.0, volume: "375ml",
        price: 22000000, old_price: null, stock: null, score: 100, rating: 5.0,
        reviews_count: 23, vintage: 2020, badge: "Quý hiếm",
        img: "images/white_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Screaming Eagle Cabernet", region: "Mỹ", subregion: "Napa Valley", type: "red",
        grape: "Cabernet Sauvignon", abv: 14.5, volume: "750ml",
        price: 75000000, old_price: null, stock: null, score: 99, rating: 5.0,
        reviews_count: 31, vintage: 2016, badge: "Huyền thoại",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Torres Gran Coronas", region: "Tây Ban Nha", subregion: "Penedès", type: "red",
        grape: "Cabernet Sauvignon / Tempranillo", abv: 13.5, volume: "750ml",
        price: 650000, old_price: 800000, stock: null, score: 89, rating: 4.4,
        reviews_count: 364, vintage: 2020, badge: "Tiết kiệm",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Cloudy Bay Te Koko", region: "New Zealand", subregion: "Marlborough", type: "white",
        grape: "Sauvignon Blanc", abv: 14.0, volume: "750ml",
        price: 1850000, old_price: 2200000, stock: null, score: 93, rating: 4.7,
        reviews_count: 148, vintage: 2020, badge: "Đặc biệt",
        img: "images/white_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Château d'Yquem", region: "Pháp", subregion: "Sauternes", type: "dessert",
        grape: "Sémillon / Sauvignon Blanc", abv: 14.0, volume: "375ml",
        price: 8500000, old_price: null, stock: null, score: 98, rating: 4.9,
        reviews_count: 76, vintage: 2015, badge: "Vang ngọt đỉnh cao",
        img: "images/dessert_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Glenfiddich 18 Year", region: "Scotland", subregion: "Speyside", type: "whisky",
        grape: null, abv: 40.0, volume: "700ml",
        price: 2100000, old_price: 2500000, stock: null, score: 91, rating: 4.6,
        reviews_count: 418, vintage: null, badge: "Bán chạy",
        img: "images/whisky_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Clos du Val Estate Chardonnay", region: "Mỹ", subregion: "Napa Valley", type: "white",
        grape: "Chardonnay", abv: 14.2, volume: "750ml",
        price: 1200000, old_price: 1450000, stock: null, score: 90, rating: 4.5,
        reviews_count: 187, vintage: 2021, badge: null,
        img: "images/white_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Pio Cesare Barolo DOCG", region: "Ý", subregion: "Barolo", type: "red",
        grape: "Nebbiolo", abv: 14.5, volume: "750ml",
        price: 3200000, old_price: 3800000, stock: null, score: 93, rating: 4.7,
        reviews_count: 134, vintage: 2018, badge: "Giảm 15%",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Baileys Original Irish Cream", region: "Ireland", subregion: null, type: "liqueur",
        grape: null, abv: 17.0, volume: "700ml",
        price: 650000, old_price: 750000, stock: null, score: 88, rating: 4.5,
        reviews_count: 862, vintage: null, badge: "Yêu thích",
        img: "images/cognac_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Hennessy VSOP Privilege", region: "Pháp", subregion: "Cognac", type: "brandy",
        grape: null, abv: 40.0, volume: "700ml",
        price: 1900000, old_price: 2200000, stock: null, score: 90, rating: 4.6,
        reviews_count: 534, vintage: null, badge: "Phổ biến",
        img: "images/cognac_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Masi Amarone della Valpolicella", region: "Ý", subregion: "Veneto", type: "red",
        grape: "Corvina / Molinara / Rondinella", abv: 15.5, volume: "750ml",
        price: 2800000, old_price: 3200000, stock: null, score: 94, rating: 4.7,
        reviews_count: 178, vintage: 2017, badge: "Đậm đà",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Kumeu River Chardonnay", region: "New Zealand", subregion: "Auckland", type: "white",
        grape: "Chardonnay", abv: 13.5, volume: "750ml",
        price: 1100000, old_price: 1300000, stock: null, score: 93, rating: 4.6,
        reviews_count: 99, vintage: 2021, badge: null,
        img: "images/white_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
    {
        name: "Caymus Cabernet Sauvignon", region: "Mỹ", subregion: "Napa Valley", type: "red",
        grape: "Cabernet Sauvignon", abv: 14.8, volume: "750ml",
        price: 3600000, old_price: 4200000, stock: null, score: 93, rating: 4.7,
        reviews_count: 289, vintage: 2021, badge: "Napa Favorite",
        img: "images/red_wine_bottle.jpg",
        description: "",
        tasting_notes: JSON.stringify({}),
        food_pairing: JSON.stringify([]),
        tags: JSON.stringify([]),
    },
];

function seed() {
  initDB();
  const db = getDB();

  const insert = db.prepare(`
    INSERT OR IGNORE INTO products
      (name,region,subregion,type,grape,abv,volume,price,old_price,stock,score,rating,reviews_count,vintage,badge,img,description,tasting_notes,food_pairing,tags)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
  `);

  const insertAll = transaction(db, (rows) => {
    rows.forEach((r) => {
      insert.run(
        r.name,
        r.region,
        r.subregion,
        r.type,
        r.grape,
        r.abv,
        r.volume,
        r.price,
        r.old_price,
        r.stock,
        r.score,
        r.rating,
        r.reviews_count,
        r.vintage,
        r.badge,
        r.img,
        r.description,
        r.tasting_notes,
        r.food_pairing,
        r.tags,
      );
    });
  });
  insertAll(products);

  // Seed admin user
  const bcrypt = require("bcryptjs");
  const adminPwd = bcrypt.hashSync("Admin@123", 10);
  db.prepare(
    `
    INSERT OR IGNORE INTO users (email, password, full_name, role, tier)
    VALUES (?, ?, 'VINOVA Admin', 'admin', 'platinum')
  `,
  ).run("admin@vinova.vn", adminPwd);

  console.log(`✅ Seeded ${products.length} products + admin user`);
  console.log("   Email: admin@vinova.vn | Password: Admin@123");
}

seed();
